- name: Déployer Nginx sur le cluster K3s
  hosts: k3s_master
  become: yes
  tasks:

    - name: Installer pip pour Python3
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Installer la bibliothèque Python kubernetes
      ansible.builtin.pip:
        name: kubernetes
        state: present

    - name: Créer le namespace (optionnel)
      kubernetes.core.k8s:
        name: demo
        api_version: v1
        kind: Namespace
        state: present
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Déployer Nginx Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-demo
            namespace: demo
            labels:
              app: nginx-demo
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: nginx-demo
            template:
              metadata:
                labels:
                  app: nginx-demo
              spec:
                containers:
                  - name: nginx
                    image: nginx:1.25
                    ports:
                      - containerPort: 80
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Créer le service NodePort pour Nginx
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: demo
          spec:
            selector:
              app: nginx-demo
            ports:
              - port: 80
                targetPort: 80
            type: NodePort
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
